### ISSUE TITLE
Unable to open apkm files

### ISSUE THREAD

**Issue by ale5000-git** [illogical-robot/apkmirror-public#188]
#### Expected behavior
Be able to install apkm from anywhere.

#### Actual behavior
The installation start only from Chrome downloads, everything else do not work.

#### Steps to reproduce the problem
I have downloaded Google Recorder apkm from Chrome and then:
- If I open it directly from Chrome downloads it open in APKMirror Installer and ask to install correctly (good).
- Instead if I open the same file from the app "Files by Google" it doesn't offer to open it with APKMirror Installer, it isn't in the list (bad); still it works correctly with other apk files.
- Also when I go in APKMirror Installer and choose browse files it list other apk and xapk but not the Google Recorder apkm (bad).

Android 10
Phone: Ulefone Armor 10 5G

**Comment by archon810** [comment]
I can reproduce the issues with Files by Google, thanks. Not sure if it's fixable, but we'll try.

> Also when I go in APKMirror Installer and choose browse files it list other apk and xapk but not the Google Recorder apkm (bad).

Can you please explain this one? I just fired up the app and it showed me a .apkm file just fine in my Downloads folder.

**Comment by archon810** [comment]
Samsung My Filese doesn't register either.

**Comment by archon810** [comment]
I believe we fixed this issue by expanding the list of file types the installer can tell Android it's able to handle. It's not an ideal fix but there is no other way due to what data is passed to us from these 3rd-party file managers and browsers.
