### ISSUE TITLE
Hidden image in footer

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#204]
#### Expected behavior
Load image or Remove Image

#### Actual behavior
One image in footer is not loading

#### Steps to reproduce the problem
Visit site and see footer
![image](https://user-images.githubusercontent.com/67194650/155657702-93d9b1ba-eff6-45be-babf-832ce733f969.png)
Image URL is: https://b.scorecardresearch.com/p?c1=2&c2=15235859&cv=2.0&cj=1

**Comment by archon810** [comment]
Do you have JS disabled and an ad blocker? This is a tracking pixel that doesn't show up broken otherwise for me. We'll push a commit to prevent this, however.
