### ISSUE TITLE
Advanced search option broken? 

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#205]
#### Expected behavior
Search option of minimum android version should work properly

#### Actual behavior
Minimum version search option is not working properly. 
![12052](https://user-images.githubusercontent.com/67194650/156739819-95db635c-3ffe-4f9f-91f6-616f50118b36.png)
I'm getting Android 5.0+ APK list when I search for Android 8.0+

#### Steps to reproduce the problem
Perform advanced search as shown in above image

**Comment by archon810** [comment]
The way this option works is it will find APKs that will work on the specified by the selectors versions of Android. In this case, the APKs are 5.0+ and they'll work on Android 8.0 - 11.0. It's a bit confusing, but we decided that this is the most useful use case for advanced search - you're providing the range for versions of Android and we return APKs that should work based on minAPI.
