### ISSUE TITLE
RT News disappeared?

### ISSUE THREAD

**Issue by abuttino** [illogical-robot/apkmirror-public#207]
#### Expected behavior
Gives apks like it did last week

#### Actual behavior
No results

#### Steps to reproduce the problem
Search for rt

Why the heck would apkmirror censor this? Never another donation from me again. This site isn't political and you just made it.

**Comment by archon810** [comment]
You can find the reasons here https://twitter.com/ArtemR/status/1499837712345432064 and here https://www.androidpolice.com/android-police-stands-with-the-people-of-ukraine/. RT and Sputnik are widely known Russian propaganda channels that were banned by many countries and services.

What donation? Apkmirror never accepted any.

Many things aren't political on the surface until people like Putler make it impossible for them to be impartial. As a Ukrainian American, I don't regret removing these apps from the site. If you're going to lodge complaints about Ukraine against various companies, you're going to have your work cut out for you, as the list of those who are sanctioning Russia in one way or another keeps growing by the minute.

**Comment by abuttino** [comment]
It's called censorship and it's not good for Truth.

You don't get to decide what's true either.

The first casualty in war is the truth.

I presume you aren't American and you don't know how many lives were lost to protect our freedoms. Fought by American Soldiers to preserve and defend the Constitution of the United States. 

Maybe we should call for the ban of apkmirror because they side with enemies. These enemies hate the U.S. and the Constitution.

Censorship is nothing other than hiding behind lies, and you are afraid the ones that you censor might open people's minds to something that you have lied about.

If RT is spreading lies, let the people decide that for themselves. This is not a nanny-state, people don't need your protection. 

There is more than 1 point of view about Russia/Ukraine, just like there was more than one argument against masks and vaccines for COVID.

History will denote every person in it's path, pushing for communism and Marxism, and I guess your site just became one of them.

Shame on you if you are a US Citizen.
