### ISSUE TITLE
Old FAQ text

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#211]
#### Expected behavior
Update FAQ with new terms for CPU architectures.
Previously on APK Pages, I used to see terms like "arm" and "arm64" in brackets.
#### Actual behavior
But now on APK pages, I see terms line "armv7a" and "arm64-v8a" in brackets.
and these terms are still in old way in FAQ.
See these lines:

- arm (armeabi, armeabi-v7a), arm64 (arm64, arm64-v8a), x86, x86_64, mips, mips64: these are CPU architectures.
- arm on arm device: OK.
- arm64 on arm device: Nope.
- arm on arm64 device: OK
- arm64 on arm64 device: OK

#### Steps to reproduce the problem
Visit FAQ page

**Comment by archon810** [comment]
I don't see an issue here. "arm", "arm64", etc. are used as descriptive terms for various architectures without having to mention each individual variant by its full name. I think everything is pretty clear as is.
