### ISSUE TITLE
Apkmirror site problem

### ISSUE THREAD

**Issue by Provat368** [illogical-robot/apkmirror-public#219]
#### Steps to reproduce the problem
Apkmirror site does not working properly the search bar not working, actually the full site kind of buggy now please chek the site and fix the problems that causes this...

**Comment by archon810** [comment]
Can you please be more specific? Are you using any kind of ad blocker that might be blocking site functionality? Can you try disabling it?

**Comment by archon810** [comment]
Will reopen if more feedback is provided.
