### ISSUE TITLE
[Question] How to patch .apkm file?

### ISSUE THREAD

**Issue by Tolsi** [illogical-robot/apkmirror-public#222]
Hi I'm trying to modify a .apk file from a .apkm package and when installing via AppMirror I get the error "App installation failed. The package archive file is invalid". I understand correctly that the .apkm file is just a zip archive with apks and metadata? What should I do after modifying and re-signing the .apk file with the application? Should I change `SHA1-Digest` in APPMIRRO.SF and MANIFEST.MF and what should they be? Can I disable this check somehow in the APKMirror Installer?

**Comment by DivineGoddess357** [comment]
My email is divinegoddess357@gmail.com if you can help me fix my phone just wrote the last text posted thanks

**Comment by Tolsi** [comment]
looks like the base apk signature was invalid
