### ISSUE TITLE
Can't upload PUBG MOBILE LITE 0.23.0 (apk from pubgmlite.com)

### ISSUE THREAD

**Issue by tienquanutc** [illogical-robot/apkmirror-public#225]
I try to upload PUBG MOBILE LITE 0.23 from pubgmlite.com. APKMirror has no files from this website yet. It is about 968MB

#### Expected behavior
A new variant adds to APKMirror.

#### Actual behavior
Thanks, but we already have a similar APK on the website: [PUBG MOBILE LITE 0.23.0 (arm-v7a) (Android 4.3+)](https://www.apkmirror.com/apk/level-infinite/pubg-mobile-lite/pubg-mobile-lite-0-23-0-release/pubg-mobile-lite-0-23-0-2-android-apk-download/)!

#### Steps to reproduce the problem
Download PUBG Mobile Lite(https://www.pubgmlite.com/en-US/).
Upload to APKMirror.
![image](https://user-images.githubusercontent.com/27769580/176817789-c81611aa-bcbd-40a1-947b-bfc0f8559222.png)

**Comment by archon810** [comment]
I disabled the similar apk check for this app, please try again.
