### ISSUE TITLE
Ads overlap on some app pages

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#229]
#### Expected behavior
Ads should not overlap content

#### Actual behavior
![image](https://user-images.githubusercontent.com/67194650/181770923-b956748d-03a6-470e-b114-0805b27def9d.png)

#### Steps to reproduce the problem
Visit
`https://www.apkmirror.com/apk/google-inc/youtube-for-android-tv-android-tv/`

**Comment by archon810** [comment]
Can reproduce this, we will fix this ASAP, thanks for reporting.

![Screenshot_20220729-070653.png](https://user-images.githubusercontent.com/469543/181777948-e1226c6c-d49c-40c7-a50d-00043428fa83.png)

**Comment by archon810** [comment]
We released a bug fix for this issue. Thank you again for reporting it.

![image](https://user-images.githubusercontent.com/469543/181787135-7f25edc3-c305-4889-9fb0-55ea6dded58c.png)
