### ISSUE TITLE
Latest Marvel Snap release not available

### ISSUE THREAD

**Issue by tawmas** [illogical-robot/apkmirror-public#236]
#### Expected behavior

The Marvel Snap page should list version 4.6.9, released on September 20, 2022, for download.

#### Actual behavior

The most recent version listed is 4.6.2, from August 9, 2022.

#### Steps to reproduce the problem

Look at https://www.apkmirror.com/apk/nuverse/marvel-snap/

**Comment by archon810** [comment]
Seeing 6.9.1 here, actually, just published. Not sure why you're seeing 4.6.9 though.
