### ISSUE TITLE
 APKMirror Installer: can not install apk due to a bug for insufficient storage space

### ISSUE THREAD

**Issue by Ascended-Master** [illogical-robot/apkmirror-public#242]
#### Expected behavior
I tried to install an APKm file "Call of Duty Season 10", the latest APK file from the APKmirror website, the version I used was 1.0.34 I think, I started the installation and waited for installation to complete, but unfortunately, it failed and also got 5-10 minutes wait for the message for installation.

#### Actual behavior
It responded to me: the installation failed because your device does not have enough storage space, I tried to free some storage space and tried again overall 3 times, and every time it consumed my internal storage first time 1.6 to 300 MB, second time 2.45 to 800 and third time 3.84 to 800 megabytes or so, I did delete everything before my third installation like deleting data and cache of many apps, also deleted many apps and even wiped my cache partition from recovery option on my SAMSUNG GALAXY TAB A (2016) with 16 Gigabytes of internal storage space. the weird part is every time I installed the APK file, even when I have moved every single picture, movie, or video to External storage space, it changes the used storage space of internal space but there are no signs of data or files, I have used Root browser app to find the files but nothing shows up, it is really strange. if there are any temporary or cache folders that the APKMirror installer is using that I missed I would be glad to know the exact paths that the app is using for opening and preparing the files for installation and how to access and delete them exactly would help solve this issue.

#### Steps to reproduce the problem
I had 3.84 Gigabytes on my Phone's Internal Storage and tried to Install an.APKM file with 2.4 Gigabyte size and unfortunately it responded with failed installation, I have used SAMSUNG GALAXY TAB A (2016), Model number: SM-T285, Android Version: 5.1.1,
I did this and tried many times using ADB and other apps for diagnosing but nothing showed up, I hope i receive the answer for this problem, truly yours

**Comment by archon810** [comment]
As I responded to you via email, I believe the files would be in Apkmirror Installer's cache. If you cleared the cache or the app data entirely, I believe that would help reclaim the space. I'm going to ask our developer(s) to chime in just in case though.

**Comment by Ascended-Master** [comment]
@archon810 @damianpiwowarski @linuxct Hello
I am still waiting for your response, I searched manually for my whole phone and found nothing about your files !! This is a serious bug and I must know what is going on, I have deleted many apps and updates like the phone is a factory reset but still nothing I lack storage space even for just one single 6 MB Application install from google play! please consider this issue very seriously and if you can as soon as possible since it is damaging my phone, I would be really glad and appreciate for response

**Comment by Ascended-Master** [comment]
@archon810 @damianpiwowarski @linuxct @SeBsZ 
No answer or update ? i did wipe My cache partition and checked everywhere seems when the battery will get delete in the installed partition which is still unknown, did you do anything about it ? i even deleted 7 G bytes after what i found out, still i get this message, what should i do ?

**Comment by Ascended-Master** [comment]
> As I responded to you via email, I believe the files would be in Apkmirror Installer's cache. If you cleared the cache or the app data entirely, I believe that would help reclaim the space. I'm going to ask our developer(s) to chime in just in case though.

so what happened finally ?

**Comment by archon810** [comment]
Another email from a user.

> Subject: Storage increased by 5gb
> 
> Message Body:
> I tried to install call of duty mobile but it was just showing installing for last 30 minutes so I cancelled it and the storage size increases by 2.5gb and then I tried again and again same issue and again 2.5 gb size increased, now my storage is full
> 
> I deleted the apk mirror installer app but still 5gb is not reducing,  I also deleted Android folder but then also it is not decreasing which means that the 5gb is in root folder , now how to delete it?

**Comment by Krisada010** [comment]
On

**Comment by archon810** [comment]
This issue was resolved in the latest release. The Installer will now properly clean up after failed installations and show a toast message with the amount of space it reclaims.

**Comment by Krisada54** [comment]
36
