### ISSUE TITLE
Hulu installation: "package appears to be corrupt"

### ISSUE THREAD

**Issue by QuestioningEspecialy** [illogical-robot/apkmirror-public#244]
Moto G4+ Android 7.0

#### Expected behavior
Selecting the apk from [File Commander](https://www.amazon.com/dp/B00A2QDM8E) (Amazon Appstore version) and installing should lead to it being fully installed without issue.

#### Actual behavior
Both [Hulu: Stream shows & movies 4.51.0+11185-google (Android 5.0+)](https://www.apkmirror.com/apk/disney/hulu-hulu/hulu-hulu-4-51-011185-google-release/hulu-stream-shows-movies-4-51-011185-google-android-apk-download/) and [Hulu: Stream shows & movies 4.49.4+10796-google (Android 5.0+)](https://www.apkmirror.com/apk/disney/hulu-hulu/hulu-hulu-4-49-410796-google-release/hulu-watch-tv-shows-movies-4-49-410796-google-android-apk-download/) apk files give me the "package appears to be corrupt" error during installation. App never successfully installs. 
Renaming to _"hulu plus_4 49 4_10796-google-4010796_minAPI21.apk"_ changes nothing.

#### Steps to reproduce the problem
PC > download apk from site > copy to phone through USB connection > open File Commander > Internal storage > select apk > Open with: Package installer > Just Once > INSTALL

**Comment by archon810** [comment]
I tested these on my Pixel 7 Pro with Android 13, and they install successfully. The files themselves are not corrupted, it's something with your specific device or Android version. Frequently, Android would say "corrupt" while in reality it just masks another error.

**Comment by polarpsy94** [comment]
> Moto G4+ Android 7.0
> 
> #### Comportamiento esperado
> Seleccionar el apk de [File Commander](https://www.amazon.com/dp/B00A2QDM8E) (versión de Amazon Appstore) e instalarlo debería llevar a que se instale completamente sin problemas.
> 
> #### Comportamiento real
> Los archivos apk de [Hulu: Stream shows & movies 4.51.0+11185-google (Android 5.0+)](https://www.apkmirror.com/apk/disney/hulu-hulu/hulu-hulu-4-51-011185-google-release/hulu-stream-shows-movies-4-51-011185-google-android-apk-download/) y [Hulu: Stream shows & movies 4.49.4+10796-google (Android 5.0+)](https://www.apkmirror.com/apk/disney/hulu-hulu/hulu-hulu-4-49-410796-google-release/hulu-watch-tv-shows-movies-4-49-410796-google-android-apk-download/) me dan el "paquete parece estar corrupto" error durante la instalación. La aplicación nunca se instala con éxito. Cambiar el nombre a _"hulu plus_4 49 4_10796-google-4010796_minAPI21.apk"_ no cambia nada.
> 
> #### Pasos para reproducir el problema
> PC> descargue apk del sitio> copie al teléfono a través de una conexión USB> abra File Commander> Almacenamiento interno> seleccione apk> Abrir con: Instalador de paquetes> Solo una vez> INSTALAR

**Comment by polarpsy94** [comment]
https://github.com/illogical-robot/apkmirror-public/issues/244#issue-1551854439
