### ISSUE TITLE
Deceptive advertising

### ISSUE THREAD

**Issue by Jpjackman** [illogical-robot/apkmirror-public#245]
#### Expected behavior
Ads appear during install

#### Actual behavior
deceptive ad claimed we had to supply cc# to proceed, cc would not be charged.  CC was immediately charged $39.95 by watha.me

**Comment by archon810** [comment]
Where was this ad, in the APKMirror Installer or the site? What did it show, do you happen to have a screenshot?

In general, we are at the mercy of Google's as network here and don't pick and choose the ads that they show.

**Comment by Jpjackman** [comment]
I was installing Play store on Fire Tablet.  Had to dl APKMirror installer v 1.3.2 directly from your site, since Google Play Store not yet installed.  Was installing Google Play Services.  Click INSTALL APP and screen came up with banner for some streaming movie service, said I had to create an account to continue.  I created account, next screen said I had to enter CC# for verification but would not be charged.  I entered number, clicked FINISH and the app immediately charged $1 and separate charge of $35 in the name of watha.me.  The bank recognized as likely fraud and declined.  

 

I tried again and waited the ad out and was able to install software – but ad was intentionally deceptive and designed to lead the viewer to believe it was part of install process.

 

John

**Comment by archon810** [comment]
I see. I'm sorry this happened, but as I said, we're at the mercy of Google's Admob network (it's the biggest advertising network app developers use on mobile). There could be a way to report individual ads that I could look into, but I'd have to figure out what the ad was for, which is hard to do without a screenshot or url. Do you happen to have any of those handy?

**Comment by Jpjackman** [comment]
Let me try to install another APK bundle and see if I can get it up.

 

John

**Comment by mznpussy** [comment]
up)

**Comment by mznpussy** [comment]
up

**Comment by archon810** [comment]
Closing due to lack of follow-up.
