### ISSUE TITLE
BYJU's Classes - Copyright Infringement Notice

### ISSUE THREAD

**Issue by Prakash36987** [illogical-robot/apkmirror-public#246]
Dear Sir / Madam:
This is a Notice in accordance with the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines) Rules, 2011 framed there under, regarding the violation of Think and Learn., (Rights Holders) exclusive rights under the Copyright Act, 1957 through the intermediarys web portal. The unauthorized distribution may also violate the Online Copyright Infringement Liability Limitation Act (OCILLA) a part of the Digital Millennium Copyright Act of 1998. 
Think and Learn., is the owner of copyright in the work of Content.
Think and Learn., is also the owner of various trademarks associated with the Content.
We have found that the Content is being illegally made available on your website which is a violation of Rights Holders exclusive rights under the Copyright Act. 
Below are the URL for your reference: 
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-0-release/homework-help-app-scan-question-get-answer-1-8-0-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-3-release/homework-help-app-scan-question-get-answer-1-8-3-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-2-release/homework-help-app-scan-question-get-answer-1-8-2-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-1-release/homework-help-app-scan-question-get-answer-1-8-1-android-apk-download/
https://www.apkmirror.com/apk/toppr/toppr-plus/toppr-plus-1-0-67-release/toppr-plus-1-0-67-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-5-release/homework-help-app-scan-question-get-answer-1-8-5-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-8-4-release/homework-help-app-scan-question-get-answer-1-8-4-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-7-4-release/homework-help-app-scan-question-get-answer-1-7-4-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-8-release/homework-help-app-scan-question-get-answer-1-6-8-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-7-release/homework-help-app-scan-question-get-answer-1-6-7-android-apk-download/
https://www.apkmirror.com/apk/toppr/toppr-plus/toppr-plus-1-0-65-release/toppr-plus-1-0-65-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-7-7-release/homework-help-app-scan-question-get-answer-1-7-7-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-7-3-release/homework-help-app-scan-question-get-answer-1-7-3-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-7-1-release/homework-help-app-scan-question-get-answer-1-7-1-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-3-release/homework-help-app-scan-question-get-answer-1-6-3-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-0-release/homework-help-app-scan-question-get-answer-1-6-0-android-apk-download/
https://www.apkmirror.com/apk/toppr/toppr-plus/toppr-plus-1-0-64-release/toppr-plus-1-0-64-android-apk-download/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-1-release/homework-help-app-scan-question-get-answer-1-6-1-android-apk-download/
https://www.apkmirror.com/apk/toppr/toppr-learning-app-for-class-5-12/toppr-learning-app-for-class-5-12-6-5-115-release/
https://www.apkmirror.com/apk/toppr/homework-help-app-scan-question-get-answer/homework-help-app-scan-question-get-answer-1-6-2-release/homework-help-app-scan-question-get-answer-1-6-2-android-apk-download/
 
In light of the foregoing, we hereby demand that you immediately cease such unlawful activities and take steps to ensure that, in the future, your Website does not infringe upon Rights Holders exclusive rights under copyright. Without limitation, we demand that you immediately cease and desist from using the Website to directly or indirectly cause, contribute to, enable, facilitate, aid, abet, induce, encourage, and/or participate in the infringement of Rights Holders copyrighted works, including but not limited to the Intellectual Property as identified.
We believe this information is sufficient for you to locate and cease the infringing activities complained about herein. We are providing this notice based on our good faith belief that the use of the content owned by Rights Holders in the manner occurring via Website is not authorized by the copyright owners, their agents, or the law. The information in this notification is accurate. 
Under penalty of perjury, we, Aiplex Software Pvt. Ltd, are the authorized Online Anti-Piracy Solution Providers write to you on behalf of Think and Learn., Our details may be found on the signature page authorized to act on behalf of the owners of the exclusive rights that are being infringed. This letter is without prejudice to the rights and remedies of Rights Holders, all of which are expressly reserved.
AUTHORIZATION LETTER FOR PROOF
https://drive.google.com/file/d/1632axXc2onA2tVhMOq8e7PCTKIm_mMJL/view
 
DIGITAL SIGNATURE FOR COPYRIGHT CLAIM
Authorized Online Antipiracy solution provider for Think and Learn.,
Prakash Kumbar
Sr. Consultant Enforcement,
Aiplex Software Private Limited,
N Cube Centre, # 91A
3rd Floor, Ideal Homes Circle
Next to Nimishambha Temple
Rajarajeshwari Nagar, Bengaluru 560 098
E-mail: dmca@aiplex.com
Website: www.aiplex.com

**Comment by archon810** [comment]
As I replied to you previously, we have permission from Toppr to host their apps. In fact, they asked us to host them. This was my contact who requested it from Toppr's side: https://www.linkedin.com/in/ian-menezes-8b58a61b.

**Comment by archon810** [comment]
Hi,

Please see below and reach out to your Toppr contacts and Ian Menezes for
further questions:

[image: image.png]

Sincerely,
Artem

--
Founder, Android Police <http://www.androidpolice.com>, APK Mirror
<http://www.apkmirror.com/>, Illogical Robot LLC
beerpla.net | @ArtemR <http://twitter.com/ArtemR>

**Comment by archon810** [comment]
Hi,

Please see below and reach out to your Toppr contacts and Ian Menezes for further questions:

![image](https://user-images.githubusercontent.com/469543/226825006-7f545066-8893-48b8-b8fb-e6c061d61689.png)
