### ISSUE TITLE
Advertisements covering the download apk options on Apkmirror

### ISSUE THREAD

**Issue by Paul0133** [illogical-robot/apkmirror-public#256]
![Screenshot_20230722_190512_Chrome](https://github.com/illogical-robot/apkmirror-public/assets/140256744/2002d2cd-c7bb-48c8-8576-c7a921a1d361)

**Comment by archon810** [comment]
Thank you for reporting. Hmm, does this happen to you all the time? I haven't been able to reproduce this myself. All the ads that are serving over the list of apks on the release page are self-contained and don't overlap.

**Comment by archon810** [comment]
This issue should now be fixed as of a few minutes ago. Please comment here if you see it again.
