### ISSUE TITLE
Paid subscription but no more  download allowed 

### ISSUE THREAD

**Issue by Sam200xz** [illogical-robot/apkmirror-public#259]

**Comment by archon810** [comment]
Can you please provide details of your issue, or better yet, use the contact form to get in touch? https://www.apkmirror.com/contact-us/

**Comment by Sam200xz** [comment]
I paid the subscription but still cant download add-ons

**Comment by archon810** [comment]
Please use the contact link above to get in touch with more details about the problem, what you paid for, and your email.

**Comment by Sam200xz** [comment]
I was asked when buying the aaad application to pay an amount to have the unlimited version, the payment was made but nothing has changed, the download of add-ons is still not possible

**Comment by archon810** [comment]
I have no idea what you're talking about. This is a bug report repo for apkmirror.com. I don't know what aaad is or what add-ons you're talking about.
