### ISSUE TITLE
GCam - BSG's Google Camera port feed not updating

### ISSUE THREAD

**Issue by PeterKW** [illogical-robot/apkmirror-public#260]
https://github.com/illogical-robot/apkmirror-public/issues/128

GCam - BSG's Google Camera port (com.google.android.GoogleCameraEng) App Updates

https://www.apkmirror.com/apk/bsg/gcam-bsgs-google-camera-port-com-google-android-googlecameraeng/#

**Comment by PeterKW** [comment]
![Screenshot_20230810-223855.png](https://github.com/illogical-robot/apkmirror-public/assets/13779157/8e9ba5ce-bc46-4d0e-918c-cf1a7bd5af02)

**Comment by PeterKW** [comment]
![Screenshot_20230810-224033.png](https://github.com/illogical-robot/apkmirror-public/assets/13779157/7092ed8a-eabb-49eb-8de0-e87c6c603407)

**Comment by archon810** [comment]
Pushbullet in general has been unreliable and needs to be re-architecture from scratch, as you already saw in the linked ticket. I'll close this one as a duplicate.

**Comment by PeterKW** [comment]
> Pushbullet in general has been unreliable and needs to be re-architecture from scratch, as you already saw in the linked ticket. I'll close this one as a duplicate. 

Is there a better way of keeping up to date? There isn't an APK mirror updating application is there?

**Comment by archon810** [comment]
You can use feeds with your favorite feed reader by appending /feed to any app url.

You can also try https://www.apkmirror.com/apk/rumboalla/apkupdater/.
