### ISSUE TITLE
[Feature Request] APKMirror Installer - Export APK file without installing

### ISSUE THREAD

**Issue by geisterfurz007** [illogical-robot/apkmirror-public#262]
Currently, the app only supports installing an app by my understanding. I have a usecase for crafting an APK file for further use from an APKM file without immediately installing it from the app however. Is there an option this could be supported in APK Mirror Installer?

**Comment by archon810** [comment]
.apkm is just a zip file, so you can just unzip the files you need from it. I don't really see a point of adding export features to the app itself.
