### ISSUE TITLE
Why???

### ISSUE THREAD

**Issue by BestKiiing** [illogical-robot/apkmirror-public#263]
BUG
for some apps it says Android 8.1 or 9+ but it just works on Android 13

**Comment by archon810** [comment]
You're going to have to be more specific. What apps are we talking about here?

**Comment by BestKiiing** [comment]
The apps for Samsung in finelock for example one the apps says 9+ Android
but only works on Android 13

**Comment by archon810** [comment]
Discussions about individual apps and APKs are beyond the scope of this repo which is meant only for bug reports for the apkmirror website or app.
