### ISSUE TITLE
Google Services Framework 5.0 missing

### ISSUE THREAD

**Issue by 1268** [illogical-robot/apkmirror-public#264]
#### Steps to reproduce the problem

https://apkmirror.com/apk/google-inc/google-services-framework

**Comment by archon810** [comment]
While you seem to be correct, and the Android 5.0 version of GSF is missing from APKMirror, this simply means nobody uploaded it in the past, and I don't have a device running Android 5.0 myself. This repo is for reporting bugs/issues with the site itself and not for content requests, so I will close this report.

**Comment by Roney455** [comment]
Mandar download apkmirror app

[Roney Neinho - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=29uyp2)	[29uyp2]

On October 1, 2023 at 19:37 GMT, Artem Russakovskii ***@***.***> wrote:

Closed [#264](https://github.com/illogical-robot/apkmirror-public/issues/264) as completed.
