### ISSUE TITLE
App misbehaviour 

### ISSUE THREAD

**Issue by aziz0744** [illogical-robot/apkmirror-public#266]
#### Expected behavior
I can easily install new version mi music player and can easily uninstall new version of mi music then use older version

#### Actual behavior
I can't able to install new version of mi music player and even can't able to uninstall the recent version of mi music player to shift on older version 

#### Steps to reproduce the problem
Please help me in uninstall mi music player I am stuck

**Comment by archon810** [comment]
Hello,

Discussions about issues with individual apps and APKs are beyond the scope of this repo which is meant only for bug reports for the APKMirror website and app.

I'm going to close this and recommend you look for help on various Android forums, Discord/IRC servers, and other relevant support locations.
