### ISSUE TITLE
Note for Xiaomi Users with MIUI Optimization enabled

### ISSUE THREAD

**Issue by VisionR1** [illogical-robot/apkmirror-public#275]
I test it in my Xiaomi Poco X3 NFC Android 10 MIUI 12 with MIUI Optimization enabled, until now not have issue

1 method with backup) I try Swift Backup and working

2 methot without backup but need knowledge) Download and install the base.apk and after in the data/app where the base installed copy&paste other components (need rename and proper permission and reboot the device)

**Comment by archon810** [comment]
Perhaps this is better suited as a comment in #116?

**Comment by Rpd92** [comment]
> I test it in my Xiaomi Poco X3 NFC Android 10 MIUI 12 with MIUI Optimization enabled, until now not have issue
> 
> 1 method with backup) I try Swift Backup and working
> 
> 2 methot without backup but need knowledge) Download and install the base.apk and after in the data/app where the base installed copy&paste other components (need rename and proper permission and reboot the device)


Could you please explain more details using the swift backup?

**Comment by VisionR1** [comment]
> > I test it in my Xiaomi Poco X3 NFC Android 10 MIUI 12 with MIUI Optimization enabled, until now not have issue
> > 
> > 1 method with backup) I try Swift Backup and working
> > 
> > 2 methot without backup but need knowledge) Download and install the base.apk and after in the data/app where the base installed copy&paste other components (need rename and proper permission and reboot the device)
> 
> 
> Could you please explain more details using the swift backup?

If I remember right, because now I'm on A11, on A10 MIUI, can't install split app, but if you download from Google play and after make a backup with Swift backup, can restore successful the backup.

**Comment by Rpd92** [comment]
I see... So i should have the backup

**Comment by VisionR1** [comment]
> I see... So i should have the backup 

Yeah.
Unfortunately the only way with Swift Backup.
