### ISSUE TITLE
Buttons can't be selected with tv remote on bbc iplayer newest version downloaded to GoogleTV

### ISSUE THREAD

**Issue by ivanskcheung** [illogical-robot/apkmirror-public#278]
#### Expected behavior
After pressing the TV remote's left or right arrow buttons, the selection area should change

#### Actual behavior
app doesn't respond to pressed tv remote buttons 

#### Steps to reproduce the problem
log in to account, then press tv remote arrow buttons

**Comment by archon810** [comment]
This issue tracker is only for bugs with APKMirror. Bugs with third party apps should be reported to their respective developers.
