### ISSUE TITLE
Provavelmente Vírus em Arquivos.

### ISSUE THREAD

**Issue by SMOKESCREE** [illogical-robot/apkmirror-public#281]
Eu baixei um apk do Google One Time Init e no HybridAnalysis no Files Collection dois arquivos que são:
com.android.vpndialogs.apk onde o antivírus Antiy detectou RiskWare[RiskTool]/Android.Skymobi com AV de 3% 
E o outro arquivo é o com.google.android.gms.location.history_1.2-3_minAPI28(nodpi)_apkmirror.com.apk onde o Antiy detectou GrayWare[AdWare]/Android.Inoco também com AV de 3%.
Utilizei o VirusTotal, Metadefender, Jotti, VirScan e não acusaram nada nem o Antiy que está disponível nesses sites(só no Metadefender é que não está disponível).

https://www.hybrid-analysis.com/sample/2dba75c02cc922c317be335806142724855a1a7419989e32b81451910c0c0a84

https://www.hybrid-analysis.com/file-collection/63b35db1fb851430bb1189fb

**Comment by archon810** [comment]
False positives are not uncommon. There are no viruses in these files, they're signed by Google.
