### ISSUE TITLE
APKMirror Installer: support hidden files/directories in file chooser

### ISSUE THREAD

**Issue by osm0sis** [illogical-robot/apkmirror-public#283]
#### Expected behavior

It should see (or have an option to show) hidden directories and files (i.e. Linux convention of a . as the first character of a file/directory name). Android's normal file chooser supports this.

#### Actual behavior

No hidden files/directories are shown in the app.

#### Steps to reproduce the problem

Create a file or directory in /sdcard called .TEST and go look in APKMirror Installer, it will not be shown.

**Comment by archon810** [comment]
Out of curiosity, why would you want to store APK files in hidden directories?

**Comment by osm0sis** [comment]
I keep all of my non-stock or sideloaded files in /sdcard/.flash/, basically I do it to hide from any apps that still try to poke around. (e.g. some historically look for Magisk*.apk or a TWRP directory).

**Comment by osm0sis** [comment]
The option now exists (thanks!) but isn't tappable, at least not on my Pixel 8 Pro, to be able to enable the new Show hidden items.

**Comment by archon810** [comment]
Hmm, it was working, but you're right, it broke between then and release. 😔

**Comment by osm0sis** [comment]
Thank Artem!
