### ISSUE TITLE
Please provide single APKs and not bundles for X/Twitter

### ISSUE THREAD

**Issue by lureedo** [illogical-robot/apkmirror-public#285]
#### Expected behavior
Like many other Apps, single APKs are being shared.

#### Actual behavior
Since few releases, only APKM bundles are being provided.

**Comment by archon810** [comment]
This is happening to many apps all of a sudden. Looks like Google stopped generating fat APKs for them entirely and only bundles will be available from now on. I suspected this day would come someday, and it looks like it has.
