### ISSUE TITLE
When browsing the site, the prompt to verify that it is a real person pops up very frequently!

### ISSUE THREAD

**Issue by DbuyCN** [illogical-robot/apkmirror-public#287]
When browsing the site, the prompt to verify that it is a real person pops up very frequently!

![2024-08-22_094247.png](https://demo-cloudflare-imgbed.pages.dev/file/578d02e2ff0f4543285ba.png)

**Comment by archon810** [comment]
Hi,

This is a bot protection measure which is enabled for numerous shady ISPs, especially those that host VPNs.
