### ISSUE TITLE
Apk mirror installer not working

### ISSUE THREAD

**Issue by ja26gu** [illogical-robot/apkmirror-public#288]
I require the Cast Receiver application on my television because it lacks a pre-installed version. However, the installation process presents a challenge due to the device being an AKPM, necessitating the APK Mirror Installer. Despite successful installation of the installer, an advertisement banner appears each time I attempt to install the APKM file. Unfortunately, the television only has arrow keys, preventing me from selecting either the consent or decline options.

**Comment by archon810** [comment]
Hi,

Can you please share a screenshot or photo of such an ad? Ads shouldn't be showing up at all on Android TV as Google prohibits them on ATV.

Are you perhaps talking about the CMP popup asking to approve ad personalization perhaps?

**Comment by ja26gu** [comment]
I am not at the tv right now but here is a screenshot of the same thing on my mobile.![Screenshot_20240826_184514_APKMirror Installer (beta).jpg](https://github.com/user-attachments/assets/98437f91-2922-40eb-bc2b-f71287087e89)

**Comment by archon810** [comment]
Thank you, we will try to reproduce and fix it in the next update.

**Comment by archon810** [comment]
We have fixed the issue, and the CMP shouldn't pop up anymore in the next release. However, we were able to use the arrow keys to navigate the CMP popup on an Android TV emulator. I guess your TV doesn't support this for some reason 🤷‍♂️.
