### ISSUE TITLE
Android A14 call recorder by appliqato not recording

### ISSUE THREAD

**Issue by Mitchweld** [illogical-robot/apkmirror-public#290]
Not recording af all. Downloaded  6.55 sam update version. No difference. Also previously when it was working was only recording my voice not the recipient. I live in nj , one party state . Please help 🙏 😢

**Comment by archon810** [comment]
Unfortunately, we cannot help with issues and bugs in individual third-party apps. This tracker is only for issues with APKMirror itself.

**Comment by Mitchweld** [comment]
I don't know what that is but ok

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
