### ISSUE TITLE
Facebook Link is not working

### ISSUE THREAD

**Issue by andyg21** [illogical-robot/apkmirror-public#291]
#### Expected behavior
Valid facebook page should be shown

#### Actual behavior
It shows "This content isn't available right now"
![image](https://github.com/user-attachments/assets/738c60c6-942f-433c-aeb1-0fd9dc894d88)

#### Steps to reproduce the problem
Visit https://www.apkmirror.com/ and click on facebook icon from "Follow APK Mirror" section

**Comment by archon810** [comment]
Yeah, Facebook has taken down the page a while ago, and all our attempts to bring it back have proven to be unsuccessful. We should remove this link.

**Comment by archon810** [comment]
The Facebook link has been removed from the sidebar.
