### ISSUE TITLE
mi Calendar won't start on Android

### ISSUE THREAD

**Issue by Boble14** [illogical-robot/apkmirror-public#294]
#### Expected behavior
Installed and expected to open and use

#### Actual behavior
Got error msg - something to affect of application had an / error - bug, wait for developer to fix

#### Steps to reproduce the problem
Try  a new install on an android (galaxy 22) device and try to open
![Screenshot_im Calendar error](https://github.com/user-attachments/assets/43f1652a-dbb4-4c33-a7b9-77c1bb992603)

**Comment by archon810** [comment]
This issue tracker is for issues with apkmirror.com or APKMirror Installer, not 3rd party apps.
