### ISSUE TITLE
[feature request] Disqus comment bubbles

### ISSUE THREAD

**Issue by haref** [illogical-robot/apkmirror-public#5]
Could you add a way to show if there are Disqus comments in the release variant section of an app?

**Comment by archon810** [comment]
Do you mean add comment bubbles in various APK and release lists? I'd like to do that, definitely, it's been on the back burner for way too long.

**Comment by haref** [comment]
I meant:
for example in https://www.apkmirror.com/apk/google-inc/youtube/youtube-11-43-54-release/ some make comments right there, but many write comments in one of the 23 "variants" are there, and I would like to know if there comments in those Variants so I won't open them all, thank you.

**Comment by archon810** [comment]
This is live.
