### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by Stanzilla** [illogical-robot/apkmirror-public#86]
#### Expected behavior
Gotta save some energy!

**Comment by archon810** [comment]
Thanks for the suggestion. Currently, there is no active plan to develop a dark mode feature. It's on the list but low priority compared to the other tasks we have waiting.

**Comment by Stanzilla** [comment]
Quick and dirty version that I made for myself https://userstyles.org/styles/169298/apkmirror-com-dark-mode

**Comment by xiao-mantou** [comment]
For PC, save your ~~ass~~ eyes - [https://darkreader.org/](url)

**Comment by archon810** [comment]
Dark mode has been rolled out and is glorious, but we added it as part of a Premium feature https://www.apkmirror.com/premium.
